services:
  db:
    image: mariadb:11.7
    container_name: url_shortener-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: url_shortener
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    container_name: url_shortener-web
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  mariadb_data: