name: CI/CD for URL Shortener

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run workflow on pull requests to the main branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set environment variables
      env:
        project_name: "URL Shortener"
        database_url: "sqlite:///./test.db"
        secret_key: "test-secret-key"

      # Step 5: Debug environment variables (Optional, for debugging purposes)
      - name: Debug environment
        run: |
          echo "Project Name: $project_name"
          echo "Database URL: $database_url"
          echo "Secret Key: $secret_key"

      # Step 6: Run tests
      - name: Run tests
        env:
          project_name: "URL Shortener"
          database_url: "sqlite:///./test.db"
          secret_key: "test-secret-key"
        run: pytest

  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Step 4: Run linter
      - name: Run Flake8
        run: flake8 --max-line-length=88 .