name: CI/CD for URL Shortener

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run workflow on pull requests to the main branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        env:
          TESTING: "TRUE"
        run: pytest

  containerize:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # Run this job only if the 'test' job succeeds

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/url_shortener:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/url_shortener:latest
